[package]
edition = "2021"
name = "km-sys"
version = "0.1.0"

[features]
default = []

# Emit linker args to link to the WDK libraries
linking = []

[dependencies]
libc = { version = "0.2.138", default-features = false }

[build-dependencies]
dotenvy = "0.15.7"
