[package]
name = "km-shared"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
km-sys = { path = "../km-sys" }

bitflags = "2.4.2"
snafu = { version = "0.8.1" }
wchar = "0.11.0"
