[package]
name = "km-shared"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
km-sys = { path = "../km-sys" }

bitflags = "1.3.2"
snafu = { version = "0.7.3", default_features = false, features = [
    "rust_1_46",
] }
wchar = "0.11.0"
