[package]
name = "km-shared"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
km-sys = { path = "../km-sys" }

bitflags = "2.5.0"
snafu = { version = "0.8.3", default-features = false }
wchar = "0.11.0"
