[package]
name = "km-sys-bindgen"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
bindgen = "0.69.4"
dotenvy = "0.15.7"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
