[package]
name = "km-sys-bindgen"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
bindgen = "0.61.0"
dotenvy = "0.15.7"
serde = { version = "1.0.150", features = ["derive"] }
toml = "0.5.9"
